CREATE TABLE IF NOT EXISTS books (
    id VARCHAR(36) PRIMARY KEY,
    isbn VARCHAR(20) NOT NULL UNIQUE,
    title VARCHAR(255) NOT NULL,
    authors TEXT NULL,
    publisher VARCHAR(150) NULL,
    published_date VARCHAR(50) NULL,
    page INT NULL,
    description TEXT NULL,
    cover_url TEXT NULL,
    category VARCHAR(100) DEFAULT 'General',
    total_stock INT NOT NULL DEFAULT 1,
    available_stock INT NOT NULL DEFAULT 1,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    deleted_at DATETIME NULL,
    INDEX idx_isbn (isbn),
    INDEX idx_category (category),
    INDEX idx_title (title),
    INDEX idx_authors (authors(191)), 
    INDEX idx_publisher (publisher),
    INDEX idx_published_date (published_date),
    INDEX idx_stock (total_stock),
    INDEX idx_available_stock (available_stock)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;